### ISSUE TITLE
Manual input for Color code with 6 digit code

### ISSUE THREAD

**Issue by lanex-victor** [qiuzongyuan/vue-pick-colors#1]
It seemed it does not reflect the change when entering 6  digit code while show alpha is enabled. Is it possible to auto convert 6 digit hex color code to 8 digit?

**Comment by qiuzongyuan** [comment]
hi, the component design is like this, are you having any trouble? I might try to fix it

**Comment by qiuzongyuan** [comment]
The next update of the component will keep the selection or enter a legal value

**Comment by qiuzongyuan** [comment]
The function of legal value verification has been added in vue-pick-colors@1.3.1
