### ISSUE TITLE
提议一个颜色输入框的功能改动

### ISSUE THREAD

**Issue by CkyShaw** [qiuzongyuan/vue-pick-colors#12]
1. 格式化HEX与RGB可以不限制其他格式的输入，可以自动转换
2. 当前的格式化可以在面板支持切换按钮自动切换

在使用中，有大量的颜色的是HEX和RGB混合输入的，相信这样的改动体验会更好，另外加入吸盘就更完美了

**Comment by qiuzongyuan** [comment]
不错的建议，可以找个时间支持一下

**Comment by qiuzongyuan** [comment]
`1.7.0`  已支持 HEX和RGB，自动转换、混合输入
