### ISSUE TITLE
Control Picker loses link to model value after value is changed.

### ISSUE THREAD

**Issue by howardah** [qiuzongyuan/vue-pick-colors#15]
Using the "Control Picker" button will update the model value only the first time that it is used. If the showPicker is set to true, the value is changed, then set to true again, the picker will have lost reference to the model value and no longer update the value.

This can be seen even on the documentation page under the Control Picker heading: https://qiuzongyuan.github.io/vue-pick-colors/use.html

**Comment by qiuzongyuan** [comment]
Hello, do you mean that after updating the value and then clicking the open button, the value cannot be updated?

**Comment by qiuzongyuan** [comment]
I have fixed it in version [1.6.2](https://www.npmjs.com/package/vue-pick-colors/v/1.6.2).

Thank you for your correction.
