### ISSUE TITLE
Returns wrong color format

### ISSUE THREAD

**Issue by T-Mike** [qiuzongyuan/vue-pick-colors#18]
Upgrading to 1.6.2, color picker returns wrong color format.
For example, this : 
`<pick-colors v-model:value="colorA" format="rgb" />`
The picker returns hsl color format.

It works fine in 1.6.1

**Comment by qiuzongyuan** [comment]
Hello, thank you for your reminder.

I have fixed it in [1.6.3](https://www.npmjs.com/package/vue-pick-colors/v/1.6.3)

I will also use test cases to avoid this from happening in the future
