### ISSUE TITLE
The default value of `popupContainer` is not `body` as documented

### ISSUE THREAD

**Issue by zam157** [qiuzongyuan/vue-pick-colors#20]
`popupContainer`的默认值并不像文档中写的那样是`body`

使用组件的时候如果不显式地传入`popupContainer="body"`弹出框容器就不会是`body`而是组件dom中的父元素

https://github.com/qiuzongyuan/vue-pick-colors/blob/eb473cc98e3dbce0926434d3ea42f7ce30ff776c/src/ColorPicker.vue#L109

**Comment by qiuzongyuan** [comment]
你好，感谢反馈，已经在 `1.6.5` 修复
