### ISSUE TITLE
`change` and `update:value` events not triggered when `value` is `undefined`

### ISSUE THREAD

**Issue by zam157** [qiuzongyuan/vue-pick-colors#28]
https://github.com/qiuzongyuan/vue-pick-colors/blob/1b8cd3f07d11f5ad68f0cc4a6219920381471558/src/ColorPicker.vue#L297C6-L302C8

父组件传入的 `value` 为 `undefined` 时就不会触发更新的事件

**Comment by qiuzongyuan** [comment]
你好，感谢你的提议，在1.7.7已经修复
