### ISSUE TITLE
建议加个鼠标松开回调事件

### ISSUE THREAD

**Issue by bello96** [qiuzongyuan/vue-pick-colors#3]

**Comment by qiuzongyuan** [comment]
具体希望是在哪松开鼠标呢？是在小色块松开（点击）还是拾取面板呢？

**Comment by bello96** [comment]
拾取面板那里













在 2023-07-22 03:07:30，"qiuzongyuan" ***@***.***> 写道：

具体希望是在哪松开鼠标呢？是在小色块松开（点击）还是拾取面板呢？

**Comment by qiuzongyuan** [comment]
我大致能知道，你是什么意思了，你觉得 `change` 事件改变触发过于频繁？

提供两个解决方案

- 对 `change ` 做防抖处理

**Comment by qiuzongyuan** [comment]
我大致能知道，你是什么意思了，你觉得 `change` 事件改变触发过于频繁？

提供两个解决方案：

- 对 `change`  事件做 `防抖` 处理

- 我可以增加面板关闭事件

**Comment by bello96** [comment]
是的，用了防抖

**Comment by qiuzongyuan** [comment]
1.5.0 版本已增加 `close-picker` 事件，具体[文档](https://github.com/qiuzongyuan/vue-pick-colors/blob/main/README-zh_CN.md)
