### ISSUE TITLE
直接显示调色面板及色块宽高设置

### ISSUE THREAD

**Issue by Firestorm01** [qiuzongyuan/vue-pick-colors#4]
- 现在需要点击色块打开面板，希望可以增加一个props直接显示调色面板。
- 希望props.size可以接收数组以设置色块的宽高
非常感谢

**Comment by qiuzongyuan** [comment]
`props.size` 是希望设置外层的色块组进行调整大小吗？

**Comment by qiuzongyuan** [comment]
`props.size`作为数组是希望设置外层的色块组进行调整大小吗？

**Comment by Firestorm01** [comment]
> `props.size`作为数组是希望设置外层的色块组进行调整大小吗？

是的，现在外层的色块组只能是正方形，希望宽高都可设置

**Comment by qiuzongyuan** [comment]
大致在这两天做一下，会增加 width、height、showPicker 属性

**Comment by qiuzongyuan** [comment]
使用 `npm i vue-pick-colors@1.5.0`，已经新增 `width`、`height`、`show-picker`

使用 `show-picker` 方式 : `v-model:show-picker` ，完全由外层传值属性控制

具体[文档](https://github.com/qiuzongyuan/vue-pick-colors/blob/main/README-zh_CN.md)

**Comment by qiuzongyuan** [comment]
这两天优化了一下弹窗效果，可以更新一下版本试试

也整了一个 [demo](https://qiuzongyuan.github.io/vue-pick-colors/zh/use.html#%E6%8E%A7%E5%88%B6%E6%8B%BE%E5%8F%96%E5%99%A8)

**Comment by Firestorm01** [comment]
非常感谢，很不错
