### ISSUE TITLE
升级后很多bug问题

### ISSUE THREAD

**Issue by popdo** [qiuzongyuan/vue-pick-colors#6]
我原来使用1.3.3一直没问题。无意升级到最新版，发现点开颜色选择器vue3就报错：

```
Popper: Detected CSS transitions on at least one of the following CSS properties: "transform", "top", "right", "bottom", "left". 

 Disable the "computeStyles" modifier's `adaptive` option to allow for smooth transitions, or remove these properties from the CSS transition declaration on the popper element if only transitioning opacity or background-color for example. 

 We recommend using the popper element as a wrapper around an inner element that can have any CSS property transitioned for animations.
```

而且颜色面板在modal中使用的话跑到最底部，看了一下z-index:9 这看起来不合理。

**Comment by qiuzongyuan** [comment]
你好：
- 第一个说的报错是 Popperjs中的，但是最新版本 `1.5.7` 是没有的
- 第二个说`z-index:9 `觉得不合理可以尝试用 v-deep 去修改，或者我可以提供一个属性去改变，但是本质的原因应该是拾取器面板渲染到哪里的问题，由 `popup-container`属性控制，默认值为`body` ，可以在下个版本增加 `false`,只渲染到自身的DOM下

**Comment by popdo** [comment]
> 你好：
> 
> * 第一个说的报错是 Popperjs中的，但是最新版本 `1.5.7` 是没有的
> * 第二个说`z-index:9 `觉得不合理可以尝试用 v-deep 去修改，或者我可以提供一个属性去改变，但是本质的原因应该是拾取器面板渲染到哪里的问题，由 `popup-container`属性控制，默认值为`body` ，可以在下个版本增加 `false`,只渲染到自身的DOM下

感谢提供这么好用的颜色选择器，我今天将vue+vite环境所有依赖都升级到最新版，即使将vue-pick-colors回退到1.3.3版 点击颜色选择器按钮 也会报上面的⚠️错误。估计是跟其它包的兼容性问题。我现在将整个package包回退正常了。

z-index的问题，如果是渲染到body 使用v-deep是无法生效的。能提供一个属性配置是最好的，再次感谢！

**Comment by qiuzongyuan** [comment]
不客气，也谢谢你反馈

试试 `vue-pick-colors@1.5.8` 

新增：

- `z-index` 属性
- 支持 `popup-container` 为 `false`
