### ISSUE TITLE
从 v1.5.7 开始和 Arco Design 中带有鼠标拖拽功能的组件冲突

### ISSUE THREAD

**Issue by TanShun** [qiuzongyuan/vue-pick-colors#9]
项目UI使用的是 Arco Design，从 v1.5.1 开始，直至 v1.5.5 这几个版本，如果页面用到了该组件，通过路由跳转至其他页面时会报错；从 v1.5.7 开始，路由跳转不会报错了，但是会和 Arco Design 中带有鼠标拖拽功能的组件冲突。例如在滑动 Slider 组件时，正常情况下，松开鼠标左键就会停止滑动，但是在页面引入该组件后，会使得松开鼠标左键后还能继续滑动，滑动操作无法释放。

**Comment by qiuzongyuan** [comment]
收到问题了，这两天帮你排查一下

**Comment by qiuzongyuan** [comment]
试试 1.6.0 版本，已经修复

**Comment by TanShun** [comment]
问题已修复，谢谢
